# Generated by Django 2.2 on 2019-04-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
