# Generated by Django 2.2 on 2019-04-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='hgender',
            field=models.BooleanField(default=False),
        ),
    ]
